### ISSUE TITLE
Input cells

### ISSUE THREAD

**Issue by mahtabbigverdi** [theislab/IMPA#1]
Hi,
In the paper, it is mentioned that untreated cells are used as the input to the model but I guess the code is not like this, there is no filter on the training dataset to only keep DMSO cells. Could you please clarify this?
Thank you for your attention and time!

**Comment by allepalma** [comment]
Hi @mahtabbigverdi,

You are very right. All validations in the paper are made transforming DMSO to drug-perturbed cells, but during training (what you see in the code) we learn to transform any perturbed cell to any other perturbed cell. This means that during training we don't only learn to transform DMSO to drug but also drug to drug. 

I am uploading the preprocessed datasets right now where a metadata file is available. That will make it easy to subset for DMSO. 

Please, let me know if I can be useful any other way!

**Comment by mahtabbigverdi** [comment]
Thanks for your helpful response!
