### ISSUE TITLE
Control token for genetic perturbations experiment

### ISSUE THREAD

**Issue by mahtabbigverdi** [theislab/IMPA#2]
Hi,
In the paper, it is mentioned that:  _" For control instances, we utilized a designated token with its corresponding embedding."_ But I couldn't find the implementation in the code base and I was curious about the values of control embedding elements, are they in the same distribution as gene2vec embeddings?

**Comment by allepalma** [comment]
Hey @mahtabbigverdi ,

In the code base you find controls embeddings initialised with zero values! But you can experiment with any kind of tokens (I also used randomly initialised values for controls and it worked similarly). 

The model should ideally figure it out how to use the control representation in the AdaIn layers. 

Please, let me know if I can help you any other way :)

NB. for drugs we used the chemical representation of DMSO

**Comment by mahtabbigverdi** [comment]
Thanks, @allepalma for your quick response, also is it possible to share the 356 cell profiler feature names discussed in the paper?

**Comment by allepalma** [comment]
@mahtabbigverdi Of course :) I will do it on Thursday. I will ping you here when they are online.

**Comment by allepalma** [comment]
Dear @mahtabbigverdi, as promised you can find the feature names [here](https://github.com/theislab/IMPA/blob/main/cellprofiler_feature_names/feature_names.csv). I downsampled to 353 features removing some extra collinearities. 

Let me know if I can do anything else for you :)

**Comment by mahtabbigverdi** [comment]
Thanks a lot
