### ISSUE TITLE
Issue Found in README Command Instructions

### ISSUE THREAD

**Issue by yangtcai** [theislab/IMPA#3]
Hi there,

Great job on your project! However, I encountered a small issue when following your README instructions. The command `conda env create environment`.yml should be corrected to `conda env create -f environment.yml`.

Overall, your work is brilliant, and I hope it gets published in a reputable journal.

**Comment by allepalma** [comment]
Hi @yangtcai,

Sorry for the late answer. Your words are really kind. Thank you for taking the time to show appreciation. 

I will correct the error and close the issue.

All the best with your future work!
